/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TopVibingSong = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'streamingLink' : IDL.Text,
  'tagline' : IDL.Opt(IDL.Text),
  'rank' : IDL.Nat,
  'artworkUrl' : IDL.Text,
  'genre' : IDL.Text,
  'artistName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SaveArtistProfileInput = IDL.Record({
  'isApproved' : IDL.Bool,
  'instagramLink' : IDL.Text,
  'profilePhoto' : ExternalBlob,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'spotifyProfile' : IDL.Text,
  'youtubeChannelLink' : IDL.Text,
  'facebookLink' : IDL.Text,
  'appleProfile' : IDL.Text,
  'profilePhotoFilename' : IDL.Text,
  'stageName' : IDL.Text,
});
export const TrackMetadata = IDL.Record({
  'title' : IDL.Text,
  'lyricist' : IDL.Text,
  'audioFile' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'composer' : IDL.Text,
  'artist' : IDL.Text,
  'producer' : IDL.Text,
  'featuredArtist' : IDL.Text,
});
export const Time = IDL.Int;
export const SongSubmissionEditInput = IDL.Record({
  'artworkBlob' : ExternalBlob,
  'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
  'title' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'lyricist' : IDL.Text,
  'spotifyLink' : IDL.Opt(IDL.Text),
  'discountCode' : IDL.Opt(IDL.Text),
  'songSubmissionId' : IDL.Text,
  'artworkFilename' : IDL.Text,
  'audioFile' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'language' : IDL.Text,
  'composer' : IDL.Text,
  'genre' : IDL.Text,
  'musicVideoLink' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'appleMusicLink' : IDL.Opt(IDL.Text),
  'producer' : IDL.Text,
  'releaseDate' : Time,
  'releaseType' : IDL.Text,
  'featuredArtist' : IDL.Text,
});
export const SongStatus = IDL.Variant({
  'pending' : IDL.Null,
  'live' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const EpisodeType = IDL.Variant({
  'full' : IDL.Null,
  'trailer' : IDL.Null,
  'bonus' : IDL.Null,
});
export const PodcastEpisodeInput = IDL.Record({
  'isPromotional' : IDL.Bool,
  'title' : IDL.Text,
  'isEighteenPlus' : IDL.Bool,
  'thumbnail' : ExternalBlob,
  'showId' : IDL.Text,
  'description' : IDL.Text,
  'artwork' : ExternalBlob,
  'seasonNumber' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
  'episodeType' : EpisodeType,
  'mediaFile' : ExternalBlob,
  'isExplicit' : IDL.Bool,
});
export const PodcastType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
});
export const Language = IDL.Variant({
  'tamil' : IDL.Null,
  'hindi' : IDL.Null,
  'other' : IDL.Null,
  'marathi' : IDL.Null,
  'gujarati' : IDL.Null,
  'punjabi' : IDL.Null,
  'malayalam' : IDL.Null,
  'kannada' : IDL.Null,
  'telugu' : IDL.Null,
  'bengali' : IDL.Null,
  'english' : IDL.Null,
});
export const PodcastCategory = IDL.Variant({
  'kidsFamily' : IDL.Null,
  'music' : IDL.Null,
  'newsPolitics' : IDL.Null,
  'other' : IDL.Null,
  'arts' : IDL.Null,
  'education' : IDL.Null,
  'religionSpirituality' : IDL.Null,
  'healthFitness' : IDL.Null,
  'tvFilm' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
  'sports' : IDL.Null,
  'comedy' : IDL.Null,
  'science' : IDL.Null,
});
export const PodcastShowInput = IDL.Record({
  'podcastType' : PodcastType,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'artwork' : ExternalBlob,
  'language' : Language,
  'category' : PodcastCategory,
});
export const SubscriptionPlan = IDL.Record({
  'redirectUrl' : IDL.Text,
  'pricePerYear' : IDL.Nat,
  'benefits' : IDL.Vec(IDL.Text),
  'planName' : IDL.Text,
});
export const FeaturedArtistSong = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
});
export const FeaturedArtist = IDL.Record({
  'id' : IDL.Nat,
  'aboutBlurb' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'songs' : IDL.Vec(FeaturedArtistSong),
  'slotIndex' : IDL.Nat,
  'artistName' : IDL.Text,
});
export const ArtistProfile = IDL.Record({
  'id' : IDL.Text,
  'isApproved' : IDL.Bool,
  'instagramLink' : IDL.Text,
  'owner' : IDL.Principal,
  'profilePhoto' : ExternalBlob,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'spotifyProfile' : IDL.Text,
  'youtubeChannelLink' : IDL.Text,
  'facebookLink' : IDL.Text,
  'appleProfile' : IDL.Text,
  'profilePhotoFilename' : IDL.Text,
  'stageName' : IDL.Text,
});
export const PodcastModerationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'live' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PodcastEpisode = IDL.Record({
  'id' : IDL.Text,
  'isPromotional' : IDL.Bool,
  'title' : IDL.Text,
  'isEighteenPlus' : IDL.Bool,
  'thumbnail' : ExternalBlob,
  'showId' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'artwork' : ExternalBlob,
  'seasonNumber' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
  'episodeType' : EpisodeType,
  'moderationStatus' : PodcastModerationStatus,
  'mediaFile' : ExternalBlob,
  'timestamp' : Time,
  'isExplicit' : IDL.Bool,
});
export const PodcastShow = IDL.Record({
  'id' : IDL.Text,
  'podcastType' : PodcastType,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'artwork' : ExternalBlob,
  'language' : Language,
  'moderationStatus' : PodcastModerationStatus,
  'timestamp' : Time,
  'category' : PodcastCategory,
  'liveLink' : IDL.Opt(IDL.Text),
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const ACRResult = IDL.Record({
  'music' : IDL.Text,
  'statusCode' : IDL.Text,
});
export const SongSubmission = IDL.Record({
  'id' : IDL.Text,
  'status' : SongStatus,
  'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
  'adminLiveLink' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'preSaveLink' : IDL.Opt(IDL.Text),
  'additionalDetails' : IDL.Text,
  'lyricist' : IDL.Text,
  'spotifyLink' : IDL.Opt(IDL.Text),
  'publicLink' : IDL.Opt(IDL.Text),
  'submitter' : IDL.Principal,
  'discountCode' : IDL.Opt(IDL.Text),
  'artworkFilename' : IDL.Text,
  'audioFile' : ExternalBlob,
  'liveStreamLink' : IDL.Opt(IDL.Text),
  'artwork' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'language' : IDL.Text,
  'composer' : IDL.Text,
  'adminComment' : IDL.Text,
  'genre' : IDL.Text,
  'musicVideoLink' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'artist' : IDL.Text,
  'appleMusicLink' : IDL.Opt(IDL.Text),
  'acrResult' : IDL.Opt(ACRResult),
  'producer' : IDL.Text,
  'releaseDate' : Time,
  'isManuallyRejected' : IDL.Bool,
  'releaseType' : IDL.Text,
  'adminRemarks' : IDL.Text,
  'featuredArtist' : IDL.Text,
});
export const VideoSubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'live' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'waiting' : IDL.Null,
});
export const VideoSubmission = IDL.Record({
  'id' : IDL.Text,
  'status' : VideoSubmissionStatus,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'userId' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'submittedAt' : Time,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'artwork' : ExternalBlob,
  'updatedAt' : Time,
  'category' : IDL.Text,
  'liveUrl' : IDL.Opt(IDL.Text),
});
export const UserCategory = IDL.Variant({
  'generalArtist' : IDL.Null,
  'generalLabel' : IDL.Null,
  'proArtist' : IDL.Null,
  'ultraArtist' : IDL.Null,
  'proLabel' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'artistId' : IDL.Text,
  'category' : UserCategory,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const PublicSongInfo = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'spotifyLink' : IDL.Opt(IDL.Text),
  'artwork' : ExternalBlob,
  'language' : IDL.Text,
  'genre' : IDL.Text,
  'musicVideoLink' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'appleMusicLink' : IDL.Opt(IDL.Text),
  'releaseDate' : Time,
  'featuredArtist' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'waiting' : IDL.Null,
});
export const VerificationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : VerificationStatus,
  'expiryExtensionDays' : IDL.Nat,
  'user' : IDL.Principal,
  'verificationApprovedTimestamp' : IDL.Opt(Time),
  'timestamp' : Time,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const FeaturedArtistInput = IDL.Record({
  'aboutBlurb' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'songs' : IDL.Vec(FeaturedArtistSong),
  'artistName' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const SongSubmissionInput = IDL.Record({
  'artworkBlob' : ExternalBlob,
  'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
  'title' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'lyricist' : IDL.Text,
  'spotifyLink' : IDL.Opt(IDL.Text),
  'discountCode' : IDL.Opt(IDL.Text),
  'artworkFilename' : IDL.Text,
  'audioBlob' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'language' : IDL.Text,
  'composer' : IDL.Text,
  'genre' : IDL.Text,
  'musicVideoLink' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'appleMusicLink' : IDL.Opt(IDL.Text),
  'producer' : IDL.Text,
  'releaseDate' : Time,
  'releaseType' : IDL.Text,
  'featuredArtist' : IDL.Text,
});
export const VideoSubmissionInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'artwork' : ExternalBlob,
  'category' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTopVibingSong' : IDL.Func([TopVibingSong], [IDL.Nat], []),
  'adminDeleteArtistProfile' : IDL.Func([IDL.Text], [], []),
  'adminDeleteSubmission' : IDL.Func([IDL.Text], [], []),
  'adminEditArtistProfile' : IDL.Func(
      [IDL.Text, SaveArtistProfileInput],
      [],
      [],
    ),
  'adminEditSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
  'adminSetSubmissionLive' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adminUpdateSubmission' : IDL.Func(
      [IDL.Text, SongStatus, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'applyForVerification' : IDL.Func([], [IDL.Text], []),
  'approveEpisode' : IDL.Func([IDL.Text], [], []),
  'approvePodcast' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUserPodcastSubmission' : IDL.Func([IDL.Principal], [], []),
  'blockUserSongSubmission' : IDL.Func([IDL.Principal], [], []),
  'createArtistProfile' : IDL.Func([SaveArtistProfileInput], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPodcastEpisode' : IDL.Func([PodcastEpisodeInput], [IDL.Text], []),
  'createPodcastShow' : IDL.Func([PodcastShowInput], [IDL.Text], []),
  'createSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
  'deleteArtistProfile' : IDL.Func([IDL.Text], [], []),
  'deleteSubscriptionPlan' : IDL.Func([IDL.Text], [], []),
  'deleteTopVibingSong' : IDL.Func([IDL.Nat], [], []),
  'deleteVideoSubmission' : IDL.Func([IDL.Text], [], []),
  'demoteFromAdmin' : IDL.Func([IDL.Principal], [], []),
  'doesUserHaveArtistProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'downgradeTeamMember' : IDL.Func([IDL.Principal], [], []),
  'downloadVideoFile' : IDL.Func([IDL.Text], [ExternalBlob], []),
  'editSongSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getActiveFeaturedArtists' : IDL.Func(
      [],
      [IDL.Vec(FeaturedArtist)],
      ['query'],
    ),
  'getAllArtistProfileOwnersForAdmin' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAllArtistProfilesForAdmin' : IDL.Func(
      [],
      [IDL.Vec(ArtistProfile)],
      ['query'],
    ),
  'getAllBlockedUsersAdmin' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllEpisodes' : IDL.Func([], [IDL.Vec(PodcastEpisode)], ['query']),
  'getAllPendingEpisodes' : IDL.Func([], [IDL.Vec(PodcastEpisode)], ['query']),
  'getAllPendingPodcasts' : IDL.Func([], [IDL.Vec(PodcastShow)], ['query']),
  'getAllPodcasts' : IDL.Func([], [IDL.Vec(PodcastShow)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllSubmissionsForAdmin' : IDL.Func(
      [],
      [IDL.Vec(SongSubmission)],
      ['query'],
    ),
  'getAllSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlan)],
      ['query'],
    ),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllTopVibingSongs' : IDL.Func([], [IDL.Vec(TopVibingSong)], ['query']),
  'getAllVideoSubmissions' : IDL.Func(
      [],
      [IDL.Vec(VideoSubmission)],
      ['query'],
    ),
  'getArtistProfileByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ArtistProfile)],
      ['query'],
    ),
  'getArtistProfileEditingAccessStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getArtistProfileIdByOwnerId' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getArtistProfilesByUserForAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ArtistProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEpisodesByShowId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PodcastEpisode)],
      ['query'],
    ),
  'getFeaturedArtists' : IDL.Func([], [IDL.Vec(FeaturedArtist)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMyArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
  'getMyEpisodes' : IDL.Func([IDL.Text], [IDL.Vec(PodcastEpisode)], ['query']),
  'getMyPodcastShows' : IDL.Func([], [IDL.Vec(PodcastShow)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'getPodcastsByCategory' : IDL.Func(
      [PodcastCategory],
      [IDL.Vec(PodcastShow)],
      ['query'],
    ),
  'getRankedTopVibingSongs' : IDL.Func([], [IDL.Vec(TopVibingSong)], ['query']),
  'getSongInfo' : IDL.Func([IDL.Text], [PublicSongInfo], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTopVibingSong' : IDL.Func([IDL.Nat], [TopVibingSong], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVideoSubmissions' : IDL.Func(
      [],
      [IDL.Vec(VideoSubmission)],
      ['query'],
    ),
  'getUsersByCategory' : IDL.Func(
      [UserCategory],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getVerificationRequestsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getWebsiteLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'handleVerificationRequest' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text, VerificationStatus],
      [],
      [],
    ),
  'isArtistProfileEditingEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isArtistVerified' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlockedPodcastSubmission' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isUserBlockedSongSubmission' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isUserTeamMember' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markEpisodeLive' : IDL.Func([IDL.Text], [], []),
  'markPodcastLive' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
  'rejectEpisode' : IDL.Func([IDL.Text], [], []),
  'rejectPodcast' : IDL.Func([IDL.Text], [], []),
  'removeWebsiteLogo' : IDL.Func([], [], []),
  'reorderTopVibingSongs' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setArtistProfileEditingAccess' : IDL.Func([IDL.Bool], [], []),
  'setFeaturedArtist' : IDL.Func([IDL.Nat, FeaturedArtistInput], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setWebsiteLogo' : IDL.Func([ExternalBlob], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitSong' : IDL.Func([SongSubmissionInput], [IDL.Text], []),
  'submitVideo' : IDL.Func([VideoSubmissionInput], [IDL.Text], []),
  'toggleFeaturedArtistSlot' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockUserPodcastSubmission' : IDL.Func([IDL.Principal], [], []),
  'unblockUserSongSubmission' : IDL.Func([IDL.Principal], [], []),
  'updateArtistProfile' : IDL.Func([IDL.Text, SaveArtistProfileInput], [], []),
  'updateSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
  'updateTopVibingSong' : IDL.Func([TopVibingSong], [], []),
  'updateUserCategory' : IDL.Func([IDL.Principal, UserCategory], [], []),
  'updateVerificationStatus' : IDL.Func(
      [IDL.Text, VerificationStatus, IDL.Nat],
      [],
      [],
    ),
  'updateVideoStatus' : IDL.Func(
      [IDL.Text, VideoSubmissionStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateVideoSubmission' : IDL.Func([VideoSubmissionInput, IDL.Text], [], []),
  'upgradeUserToTeamMember' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TopVibingSong = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'streamingLink' : IDL.Text,
    'tagline' : IDL.Opt(IDL.Text),
    'rank' : IDL.Nat,
    'artworkUrl' : IDL.Text,
    'genre' : IDL.Text,
    'artistName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SaveArtistProfileInput = IDL.Record({
    'isApproved' : IDL.Bool,
    'instagramLink' : IDL.Text,
    'profilePhoto' : ExternalBlob,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'spotifyProfile' : IDL.Text,
    'youtubeChannelLink' : IDL.Text,
    'facebookLink' : IDL.Text,
    'appleProfile' : IDL.Text,
    'profilePhotoFilename' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const TrackMetadata = IDL.Record({
    'title' : IDL.Text,
    'lyricist' : IDL.Text,
    'audioFile' : ExternalBlob,
    'audioFilename' : IDL.Text,
    'composer' : IDL.Text,
    'artist' : IDL.Text,
    'producer' : IDL.Text,
    'featuredArtist' : IDL.Text,
  });
  const Time = IDL.Int;
  const SongSubmissionEditInput = IDL.Record({
    'artworkBlob' : ExternalBlob,
    'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
    'title' : IDL.Text,
    'additionalDetails' : IDL.Text,
    'lyricist' : IDL.Text,
    'spotifyLink' : IDL.Opt(IDL.Text),
    'discountCode' : IDL.Opt(IDL.Text),
    'songSubmissionId' : IDL.Text,
    'artworkFilename' : IDL.Text,
    'audioFile' : ExternalBlob,
    'audioFilename' : IDL.Text,
    'language' : IDL.Text,
    'composer' : IDL.Text,
    'genre' : IDL.Text,
    'musicVideoLink' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'appleMusicLink' : IDL.Opt(IDL.Text),
    'producer' : IDL.Text,
    'releaseDate' : Time,
    'releaseType' : IDL.Text,
    'featuredArtist' : IDL.Text,
  });
  const SongStatus = IDL.Variant({
    'pending' : IDL.Null,
    'live' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const EpisodeType = IDL.Variant({
    'full' : IDL.Null,
    'trailer' : IDL.Null,
    'bonus' : IDL.Null,
  });
  const PodcastEpisodeInput = IDL.Record({
    'isPromotional' : IDL.Bool,
    'title' : IDL.Text,
    'isEighteenPlus' : IDL.Bool,
    'thumbnail' : ExternalBlob,
    'showId' : IDL.Text,
    'description' : IDL.Text,
    'artwork' : ExternalBlob,
    'seasonNumber' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
    'episodeType' : EpisodeType,
    'mediaFile' : ExternalBlob,
    'isExplicit' : IDL.Bool,
  });
  const PodcastType = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
  const Language = IDL.Variant({
    'tamil' : IDL.Null,
    'hindi' : IDL.Null,
    'other' : IDL.Null,
    'marathi' : IDL.Null,
    'gujarati' : IDL.Null,
    'punjabi' : IDL.Null,
    'malayalam' : IDL.Null,
    'kannada' : IDL.Null,
    'telugu' : IDL.Null,
    'bengali' : IDL.Null,
    'english' : IDL.Null,
  });
  const PodcastCategory = IDL.Variant({
    'kidsFamily' : IDL.Null,
    'music' : IDL.Null,
    'newsPolitics' : IDL.Null,
    'other' : IDL.Null,
    'arts' : IDL.Null,
    'education' : IDL.Null,
    'religionSpirituality' : IDL.Null,
    'healthFitness' : IDL.Null,
    'tvFilm' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
    'sports' : IDL.Null,
    'comedy' : IDL.Null,
    'science' : IDL.Null,
  });
  const PodcastShowInput = IDL.Record({
    'podcastType' : PodcastType,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'artwork' : ExternalBlob,
    'language' : Language,
    'category' : PodcastCategory,
  });
  const SubscriptionPlan = IDL.Record({
    'redirectUrl' : IDL.Text,
    'pricePerYear' : IDL.Nat,
    'benefits' : IDL.Vec(IDL.Text),
    'planName' : IDL.Text,
  });
  const FeaturedArtistSong = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
  });
  const FeaturedArtist = IDL.Record({
    'id' : IDL.Nat,
    'aboutBlurb' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'songs' : IDL.Vec(FeaturedArtistSong),
    'slotIndex' : IDL.Nat,
    'artistName' : IDL.Text,
  });
  const ArtistProfile = IDL.Record({
    'id' : IDL.Text,
    'isApproved' : IDL.Bool,
    'instagramLink' : IDL.Text,
    'owner' : IDL.Principal,
    'profilePhoto' : ExternalBlob,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'spotifyProfile' : IDL.Text,
    'youtubeChannelLink' : IDL.Text,
    'facebookLink' : IDL.Text,
    'appleProfile' : IDL.Text,
    'profilePhotoFilename' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const PodcastModerationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'live' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PodcastEpisode = IDL.Record({
    'id' : IDL.Text,
    'isPromotional' : IDL.Bool,
    'title' : IDL.Text,
    'isEighteenPlus' : IDL.Bool,
    'thumbnail' : ExternalBlob,
    'showId' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'artwork' : ExternalBlob,
    'seasonNumber' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
    'episodeType' : EpisodeType,
    'moderationStatus' : PodcastModerationStatus,
    'mediaFile' : ExternalBlob,
    'timestamp' : Time,
    'isExplicit' : IDL.Bool,
  });
  const PodcastShow = IDL.Record({
    'id' : IDL.Text,
    'podcastType' : PodcastType,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'artwork' : ExternalBlob,
    'language' : Language,
    'moderationStatus' : PodcastModerationStatus,
    'timestamp' : Time,
    'category' : PodcastCategory,
    'liveLink' : IDL.Opt(IDL.Text),
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const ACRResult = IDL.Record({ 'music' : IDL.Text, 'statusCode' : IDL.Text });
  const SongSubmission = IDL.Record({
    'id' : IDL.Text,
    'status' : SongStatus,
    'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
    'adminLiveLink' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'preSaveLink' : IDL.Opt(IDL.Text),
    'additionalDetails' : IDL.Text,
    'lyricist' : IDL.Text,
    'spotifyLink' : IDL.Opt(IDL.Text),
    'publicLink' : IDL.Opt(IDL.Text),
    'submitter' : IDL.Principal,
    'discountCode' : IDL.Opt(IDL.Text),
    'artworkFilename' : IDL.Text,
    'audioFile' : ExternalBlob,
    'liveStreamLink' : IDL.Opt(IDL.Text),
    'artwork' : ExternalBlob,
    'audioFilename' : IDL.Text,
    'language' : IDL.Text,
    'composer' : IDL.Text,
    'adminComment' : IDL.Text,
    'genre' : IDL.Text,
    'musicVideoLink' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'artist' : IDL.Text,
    'appleMusicLink' : IDL.Opt(IDL.Text),
    'acrResult' : IDL.Opt(ACRResult),
    'producer' : IDL.Text,
    'releaseDate' : Time,
    'isManuallyRejected' : IDL.Bool,
    'releaseType' : IDL.Text,
    'adminRemarks' : IDL.Text,
    'featuredArtist' : IDL.Text,
  });
  const VideoSubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'live' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const VideoSubmission = IDL.Record({
    'id' : IDL.Text,
    'status' : VideoSubmissionStatus,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'userId' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'submittedAt' : Time,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'artwork' : ExternalBlob,
    'updatedAt' : Time,
    'category' : IDL.Text,
    'liveUrl' : IDL.Opt(IDL.Text),
  });
  const UserCategory = IDL.Variant({
    'generalArtist' : IDL.Null,
    'generalLabel' : IDL.Null,
    'proArtist' : IDL.Null,
    'ultraArtist' : IDL.Null,
    'proLabel' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'artistId' : IDL.Text,
    'category' : UserCategory,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const PublicSongInfo = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'spotifyLink' : IDL.Opt(IDL.Text),
    'artwork' : ExternalBlob,
    'language' : IDL.Text,
    'genre' : IDL.Text,
    'musicVideoLink' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'appleMusicLink' : IDL.Opt(IDL.Text),
    'releaseDate' : Time,
    'featuredArtist' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const VerificationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : VerificationStatus,
    'expiryExtensionDays' : IDL.Nat,
    'user' : IDL.Principal,
    'verificationApprovedTimestamp' : IDL.Opt(Time),
    'timestamp' : Time,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const FeaturedArtistInput = IDL.Record({
    'aboutBlurb' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'songs' : IDL.Vec(FeaturedArtistSong),
    'artistName' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const SongSubmissionInput = IDL.Record({
    'artworkBlob' : ExternalBlob,
    'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
    'title' : IDL.Text,
    'additionalDetails' : IDL.Text,
    'lyricist' : IDL.Text,
    'spotifyLink' : IDL.Opt(IDL.Text),
    'discountCode' : IDL.Opt(IDL.Text),
    'artworkFilename' : IDL.Text,
    'audioBlob' : ExternalBlob,
    'audioFilename' : IDL.Text,
    'language' : IDL.Text,
    'composer' : IDL.Text,
    'genre' : IDL.Text,
    'musicVideoLink' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'appleMusicLink' : IDL.Opt(IDL.Text),
    'producer' : IDL.Text,
    'releaseDate' : Time,
    'releaseType' : IDL.Text,
    'featuredArtist' : IDL.Text,
  });
  const VideoSubmissionInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'artwork' : ExternalBlob,
    'category' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTopVibingSong' : IDL.Func([TopVibingSong], [IDL.Nat], []),
    'adminDeleteArtistProfile' : IDL.Func([IDL.Text], [], []),
    'adminDeleteSubmission' : IDL.Func([IDL.Text], [], []),
    'adminEditArtistProfile' : IDL.Func(
        [IDL.Text, SaveArtistProfileInput],
        [],
        [],
      ),
    'adminEditSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
    'adminSetSubmissionLive' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminUpdateSubmission' : IDL.Func(
        [IDL.Text, SongStatus, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'applyForVerification' : IDL.Func([], [IDL.Text], []),
    'approveEpisode' : IDL.Func([IDL.Text], [], []),
    'approvePodcast' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUserPodcastSubmission' : IDL.Func([IDL.Principal], [], []),
    'blockUserSongSubmission' : IDL.Func([IDL.Principal], [], []),
    'createArtistProfile' : IDL.Func([SaveArtistProfileInput], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPodcastEpisode' : IDL.Func([PodcastEpisodeInput], [IDL.Text], []),
    'createPodcastShow' : IDL.Func([PodcastShowInput], [IDL.Text], []),
    'createSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
    'deleteArtistProfile' : IDL.Func([IDL.Text], [], []),
    'deleteSubscriptionPlan' : IDL.Func([IDL.Text], [], []),
    'deleteTopVibingSong' : IDL.Func([IDL.Nat], [], []),
    'deleteVideoSubmission' : IDL.Func([IDL.Text], [], []),
    'demoteFromAdmin' : IDL.Func([IDL.Principal], [], []),
    'doesUserHaveArtistProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'downgradeTeamMember' : IDL.Func([IDL.Principal], [], []),
    'downloadVideoFile' : IDL.Func([IDL.Text], [ExternalBlob], []),
    'editSongSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getActiveFeaturedArtists' : IDL.Func(
        [],
        [IDL.Vec(FeaturedArtist)],
        ['query'],
      ),
    'getAllArtistProfileOwnersForAdmin' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllArtistProfilesForAdmin' : IDL.Func(
        [],
        [IDL.Vec(ArtistProfile)],
        ['query'],
      ),
    'getAllBlockedUsersAdmin' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllEpisodes' : IDL.Func([], [IDL.Vec(PodcastEpisode)], ['query']),
    'getAllPendingEpisodes' : IDL.Func(
        [],
        [IDL.Vec(PodcastEpisode)],
        ['query'],
      ),
    'getAllPendingPodcasts' : IDL.Func([], [IDL.Vec(PodcastShow)], ['query']),
    'getAllPodcasts' : IDL.Func([], [IDL.Vec(PodcastShow)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllSubmissionsForAdmin' : IDL.Func(
        [],
        [IDL.Vec(SongSubmission)],
        ['query'],
      ),
    'getAllSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllTopVibingSongs' : IDL.Func([], [IDL.Vec(TopVibingSong)], ['query']),
    'getAllVideoSubmissions' : IDL.Func(
        [],
        [IDL.Vec(VideoSubmission)],
        ['query'],
      ),
    'getArtistProfileByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ArtistProfile)],
        ['query'],
      ),
    'getArtistProfileEditingAccessStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getArtistProfileIdByOwnerId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getArtistProfilesByUserForAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ArtistProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEpisodesByShowId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PodcastEpisode)],
        ['query'],
      ),
    'getFeaturedArtists' : IDL.Func([], [IDL.Vec(FeaturedArtist)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMyArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
    'getMyEpisodes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PodcastEpisode)],
        ['query'],
      ),
    'getMyPodcastShows' : IDL.Func([], [IDL.Vec(PodcastShow)], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
    'getPodcastsByCategory' : IDL.Func(
        [PodcastCategory],
        [IDL.Vec(PodcastShow)],
        ['query'],
      ),
    'getRankedTopVibingSongs' : IDL.Func(
        [],
        [IDL.Vec(TopVibingSong)],
        ['query'],
      ),
    'getSongInfo' : IDL.Func([IDL.Text], [PublicSongInfo], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTopVibingSong' : IDL.Func([IDL.Nat], [TopVibingSong], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVideoSubmissions' : IDL.Func(
        [],
        [IDL.Vec(VideoSubmission)],
        ['query'],
      ),
    'getUsersByCategory' : IDL.Func(
        [UserCategory],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getVerificationRequestsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getWebsiteLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'handleVerificationRequest' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text, VerificationStatus],
        [],
        [],
      ),
    'isArtistProfileEditingEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isArtistVerified' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlockedPodcastSubmission' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isUserBlockedSongSubmission' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isUserTeamMember' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markEpisodeLive' : IDL.Func([IDL.Text], [], []),
    'markPodcastLive' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
    'rejectEpisode' : IDL.Func([IDL.Text], [], []),
    'rejectPodcast' : IDL.Func([IDL.Text], [], []),
    'removeWebsiteLogo' : IDL.Func([], [], []),
    'reorderTopVibingSongs' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setArtistProfileEditingAccess' : IDL.Func([IDL.Bool], [], []),
    'setFeaturedArtist' : IDL.Func([IDL.Nat, FeaturedArtistInput], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setWebsiteLogo' : IDL.Func([ExternalBlob], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitSong' : IDL.Func([SongSubmissionInput], [IDL.Text], []),
    'submitVideo' : IDL.Func([VideoSubmissionInput], [IDL.Text], []),
    'toggleFeaturedArtistSlot' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockUserPodcastSubmission' : IDL.Func([IDL.Principal], [], []),
    'unblockUserSongSubmission' : IDL.Func([IDL.Principal], [], []),
    'updateArtistProfile' : IDL.Func(
        [IDL.Text, SaveArtistProfileInput],
        [],
        [],
      ),
    'updateSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
    'updateTopVibingSong' : IDL.Func([TopVibingSong], [], []),
    'updateUserCategory' : IDL.Func([IDL.Principal, UserCategory], [], []),
    'updateVerificationStatus' : IDL.Func(
        [IDL.Text, VerificationStatus, IDL.Nat],
        [],
        [],
      ),
    'updateVideoStatus' : IDL.Func(
        [IDL.Text, VideoSubmissionStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateVideoSubmission' : IDL.Func(
        [VideoSubmissionInput, IDL.Text],
        [],
        [],
      ),
    'upgradeUserToTeamMember' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };