/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ACRResult { 'music' : string, 'statusCode' : string }
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ArtistProfile {
  'id' : string,
  'isApproved' : boolean,
  'instagramLink' : string,
  'owner' : Principal,
  'profilePhoto' : ExternalBlob,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'isVerified' : boolean,
  'spotifyProfile' : string,
  'youtubeChannelLink' : string,
  'facebookLink' : string,
  'appleProfile' : string,
  'profilePhotoFilename' : string,
  'stageName' : string,
}
export type EpisodeType = { 'full' : null } |
  { 'trailer' : null } |
  { 'bonus' : null };
export type ExternalBlob = Uint8Array;
export interface FeaturedArtist {
  'id' : bigint,
  'aboutBlurb' : string,
  'photoUrl' : string,
  'isActive' : boolean,
  'songs' : Array<FeaturedArtistSong>,
  'slotIndex' : bigint,
  'artistName' : string,
}
export interface FeaturedArtistInput {
  'aboutBlurb' : string,
  'photoUrl' : string,
  'isActive' : boolean,
  'songs' : Array<FeaturedArtistSong>,
  'artistName' : string,
}
export interface FeaturedArtistSong { 'title' : string, 'link' : string }
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type Language = { 'tamil' : null } |
  { 'hindi' : null } |
  { 'other' : null } |
  { 'marathi' : null } |
  { 'gujarati' : null } |
  { 'punjabi' : null } |
  { 'malayalam' : null } |
  { 'kannada' : null } |
  { 'telugu' : null } |
  { 'bengali' : null } |
  { 'english' : null };
export type PodcastCategory = { 'kidsFamily' : null } |
  { 'music' : null } |
  { 'newsPolitics' : null } |
  { 'other' : null } |
  { 'arts' : null } |
  { 'education' : null } |
  { 'religionSpirituality' : null } |
  { 'healthFitness' : null } |
  { 'tvFilm' : null } |
  { 'technology' : null } |
  { 'business' : null } |
  { 'sports' : null } |
  { 'comedy' : null } |
  { 'science' : null };
export interface PodcastEpisode {
  'id' : string,
  'isPromotional' : boolean,
  'title' : string,
  'isEighteenPlus' : boolean,
  'thumbnail' : ExternalBlob,
  'showId' : string,
  'createdBy' : Principal,
  'description' : string,
  'artwork' : ExternalBlob,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'episodeType' : EpisodeType,
  'moderationStatus' : PodcastModerationStatus,
  'mediaFile' : ExternalBlob,
  'timestamp' : Time,
  'isExplicit' : boolean,
}
export interface PodcastEpisodeInput {
  'isPromotional' : boolean,
  'title' : string,
  'isEighteenPlus' : boolean,
  'thumbnail' : ExternalBlob,
  'showId' : string,
  'description' : string,
  'artwork' : ExternalBlob,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'episodeType' : EpisodeType,
  'mediaFile' : ExternalBlob,
  'isExplicit' : boolean,
}
export type PodcastModerationStatus = { 'pending' : null } |
  { 'live' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PodcastShow {
  'id' : string,
  'podcastType' : PodcastType,
  'title' : string,
  'createdBy' : Principal,
  'description' : string,
  'artwork' : ExternalBlob,
  'language' : Language,
  'moderationStatus' : PodcastModerationStatus,
  'timestamp' : Time,
  'category' : PodcastCategory,
  'liveLink' : [] | [string],
}
export interface PodcastShowInput {
  'podcastType' : PodcastType,
  'title' : string,
  'description' : string,
  'artwork' : ExternalBlob,
  'language' : Language,
  'category' : PodcastCategory,
}
export type PodcastType = { 'audio' : null } |
  { 'video' : null };
export interface PublicSongInfo {
  'id' : string,
  'title' : string,
  'spotifyLink' : [] | [string],
  'artwork' : ExternalBlob,
  'language' : string,
  'genre' : string,
  'musicVideoLink' : [] | [string],
  'artist' : string,
  'appleMusicLink' : [] | [string],
  'releaseDate' : Time,
  'featuredArtist' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface SaveArtistProfileInput {
  'isApproved' : boolean,
  'instagramLink' : string,
  'profilePhoto' : ExternalBlob,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'spotifyProfile' : string,
  'youtubeChannelLink' : string,
  'facebookLink' : string,
  'appleProfile' : string,
  'profilePhotoFilename' : string,
  'stageName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SongStatus = { 'pending' : null } |
  { 'live' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface SongSubmission {
  'id' : string,
  'status' : SongStatus,
  'albumTracks' : [] | [Array<TrackMetadata>],
  'adminLiveLink' : [] | [string],
  'title' : string,
  'preSaveLink' : [] | [string],
  'additionalDetails' : string,
  'lyricist' : string,
  'spotifyLink' : [] | [string],
  'publicLink' : [] | [string],
  'submitter' : Principal,
  'discountCode' : [] | [string],
  'artworkFilename' : string,
  'audioFile' : ExternalBlob,
  'liveStreamLink' : [] | [string],
  'artwork' : ExternalBlob,
  'audioFilename' : string,
  'language' : string,
  'composer' : string,
  'adminComment' : string,
  'genre' : string,
  'musicVideoLink' : [] | [string],
  'timestamp' : Time,
  'artist' : string,
  'appleMusicLink' : [] | [string],
  'acrResult' : [] | [ACRResult],
  'producer' : string,
  'releaseDate' : Time,
  'isManuallyRejected' : boolean,
  'releaseType' : string,
  'adminRemarks' : string,
  'featuredArtist' : string,
}
export interface SongSubmissionEditInput {
  'artworkBlob' : ExternalBlob,
  'albumTracks' : [] | [Array<TrackMetadata>],
  'title' : string,
  'additionalDetails' : string,
  'lyricist' : string,
  'spotifyLink' : [] | [string],
  'discountCode' : [] | [string],
  'songSubmissionId' : string,
  'artworkFilename' : string,
  'audioFile' : ExternalBlob,
  'audioFilename' : string,
  'language' : string,
  'composer' : string,
  'genre' : string,
  'musicVideoLink' : [] | [string],
  'artist' : string,
  'appleMusicLink' : [] | [string],
  'producer' : string,
  'releaseDate' : Time,
  'releaseType' : string,
  'featuredArtist' : string,
}
export interface SongSubmissionInput {
  'artworkBlob' : ExternalBlob,
  'albumTracks' : [] | [Array<TrackMetadata>],
  'title' : string,
  'additionalDetails' : string,
  'lyricist' : string,
  'spotifyLink' : [] | [string],
  'discountCode' : [] | [string],
  'artworkFilename' : string,
  'audioBlob' : ExternalBlob,
  'audioFilename' : string,
  'language' : string,
  'composer' : string,
  'genre' : string,
  'musicVideoLink' : [] | [string],
  'artist' : string,
  'appleMusicLink' : [] | [string],
  'producer' : string,
  'releaseDate' : Time,
  'releaseType' : string,
  'featuredArtist' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionPlan {
  'redirectUrl' : string,
  'pricePerYear' : bigint,
  'benefits' : Array<string>,
  'planName' : string,
}
export type Time = bigint;
export interface TopVibingSong {
  'id' : bigint,
  'title' : string,
  'streamingLink' : string,
  'tagline' : [] | [string],
  'rank' : bigint,
  'artworkUrl' : string,
  'genre' : string,
  'artistName' : string,
}
export interface TrackMetadata {
  'title' : string,
  'lyricist' : string,
  'audioFile' : ExternalBlob,
  'audioFilename' : string,
  'composer' : string,
  'artist' : string,
  'producer' : string,
  'featuredArtist' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserCategory = { 'generalArtist' : null } |
  { 'generalLabel' : null } |
  { 'proArtist' : null } |
  { 'ultraArtist' : null } |
  { 'proLabel' : null };
export interface UserProfile {
  'name' : string,
  'artistId' : string,
  'category' : UserCategory,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationRequest {
  'id' : string,
  'status' : VerificationStatus,
  'expiryExtensionDays' : bigint,
  'user' : Principal,
  'verificationApprovedTimestamp' : [] | [Time],
  'timestamp' : Time,
}
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'waiting' : null };
export interface VideoSubmission {
  'id' : string,
  'status' : VideoSubmissionStatus,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'userId' : Principal,
  'tags' : Array<string>,
  'submittedAt' : Time,
  'description' : string,
  'videoFile' : ExternalBlob,
  'artwork' : ExternalBlob,
  'updatedAt' : Time,
  'category' : string,
  'liveUrl' : [] | [string],
}
export interface VideoSubmissionInput {
  'title' : string,
  'thumbnail' : ExternalBlob,
  'tags' : Array<string>,
  'description' : string,
  'videoFile' : ExternalBlob,
  'artwork' : ExternalBlob,
  'category' : string,
}
export type VideoSubmissionStatus = { 'pending' : null } |
  { 'live' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'waiting' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTopVibingSong' : ActorMethod<[TopVibingSong], bigint>,
  'adminDeleteArtistProfile' : ActorMethod<[string], undefined>,
  'adminDeleteSubmission' : ActorMethod<[string], undefined>,
  'adminEditArtistProfile' : ActorMethod<
    [string, SaveArtistProfileInput],
    undefined
  >,
  'adminEditSubmission' : ActorMethod<[SongSubmissionEditInput], undefined>,
  'adminSetSubmissionLive' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'adminUpdateSubmission' : ActorMethod<
    [string, SongStatus, string, string],
    undefined
  >,
  'applyForVerification' : ActorMethod<[], string>,
  'approveEpisode' : ActorMethod<[string], undefined>,
  'approvePodcast' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUserPodcastSubmission' : ActorMethod<[Principal], undefined>,
  'blockUserSongSubmission' : ActorMethod<[Principal], undefined>,
  'createArtistProfile' : ActorMethod<[SaveArtistProfileInput], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPodcastEpisode' : ActorMethod<[PodcastEpisodeInput], string>,
  'createPodcastShow' : ActorMethod<[PodcastShowInput], string>,
  'createSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'deleteArtistProfile' : ActorMethod<[string], undefined>,
  'deleteSubscriptionPlan' : ActorMethod<[string], undefined>,
  'deleteTopVibingSong' : ActorMethod<[bigint], undefined>,
  'deleteVideoSubmission' : ActorMethod<[string], undefined>,
  'demoteFromAdmin' : ActorMethod<[Principal], undefined>,
  'doesUserHaveArtistProfile' : ActorMethod<[Principal], boolean>,
  'downgradeTeamMember' : ActorMethod<[Principal], undefined>,
  'downloadVideoFile' : ActorMethod<[string], ExternalBlob>,
  'editSongSubmission' : ActorMethod<[SongSubmissionEditInput], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActiveFeaturedArtists' : ActorMethod<[], Array<FeaturedArtist>>,
  'getAllArtistProfileOwnersForAdmin' : ActorMethod<[], Array<Principal>>,
  'getAllArtistProfilesForAdmin' : ActorMethod<[], Array<ArtistProfile>>,
  'getAllBlockedUsersAdmin' : ActorMethod<[], Array<Principal>>,
  'getAllEpisodes' : ActorMethod<[], Array<PodcastEpisode>>,
  'getAllPendingEpisodes' : ActorMethod<[], Array<PodcastEpisode>>,
  'getAllPendingPodcasts' : ActorMethod<[], Array<PodcastShow>>,
  'getAllPodcasts' : ActorMethod<[], Array<PodcastShow>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllSubmissionsForAdmin' : ActorMethod<[], Array<SongSubmission>>,
  'getAllSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getAllTeamMembers' : ActorMethod<[], Array<Principal>>,
  'getAllTopVibingSongs' : ActorMethod<[], Array<TopVibingSong>>,
  'getAllVideoSubmissions' : ActorMethod<[], Array<VideoSubmission>>,
  'getArtistProfileByOwner' : ActorMethod<[Principal], [] | [ArtistProfile]>,
  'getArtistProfileEditingAccessStatus' : ActorMethod<[], boolean>,
  'getArtistProfileIdByOwnerId' : ActorMethod<[Principal], [] | [string]>,
  'getArtistProfilesByUserForAdmin' : ActorMethod<
    [Principal],
    Array<ArtistProfile>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEpisodesByShowId' : ActorMethod<[string], Array<PodcastEpisode>>,
  'getFeaturedArtists' : ActorMethod<[], Array<FeaturedArtist>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMyArtistProfiles' : ActorMethod<[], Array<ArtistProfile>>,
  'getMyEpisodes' : ActorMethod<[string], Array<PodcastEpisode>>,
  'getMyPodcastShows' : ActorMethod<[], Array<PodcastShow>>,
  'getMySubmissions' : ActorMethod<[], Array<SongSubmission>>,
  'getPodcastsByCategory' : ActorMethod<[PodcastCategory], Array<PodcastShow>>,
  'getRankedTopVibingSongs' : ActorMethod<[], Array<TopVibingSong>>,
  'getSongInfo' : ActorMethod<[string], PublicSongInfo>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopVibingSong' : ActorMethod<[bigint], TopVibingSong>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideoSubmissions' : ActorMethod<[], Array<VideoSubmission>>,
  'getUsersByCategory' : ActorMethod<[UserCategory], Array<UserProfile>>,
  'getVerificationRequests' : ActorMethod<[], Array<VerificationRequest>>,
  'getVerificationRequestsByUser' : ActorMethod<
    [Principal],
    Array<VerificationRequest>
  >,
  'getWebsiteLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'handleVerificationRequest' : ActorMethod<
    [string, boolean, string, VerificationStatus],
    undefined
  >,
  'isArtistProfileEditingEnabled' : ActorMethod<[], boolean>,
  'isArtistVerified' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserBlockedPodcastSubmission' : ActorMethod<[Principal], boolean>,
  'isUserBlockedSongSubmission' : ActorMethod<[Principal], boolean>,
  'isUserTeamMember' : ActorMethod<[Principal], boolean>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markEpisodeLive' : ActorMethod<[string], undefined>,
  'markPodcastLive' : ActorMethod<[string, string], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'rejectEpisode' : ActorMethod<[string], undefined>,
  'rejectPodcast' : ActorMethod<[string], undefined>,
  'removeWebsiteLogo' : ActorMethod<[], undefined>,
  'reorderTopVibingSongs' : ActorMethod<[Array<bigint>], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setArtistProfileEditingAccess' : ActorMethod<[boolean], undefined>,
  'setFeaturedArtist' : ActorMethod<[bigint, FeaturedArtistInput], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWebsiteLogo' : ActorMethod<[ExternalBlob], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'submitSong' : ActorMethod<[SongSubmissionInput], string>,
  'submitVideo' : ActorMethod<[VideoSubmissionInput], string>,
  'toggleFeaturedArtistSlot' : ActorMethod<[bigint, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockUserPodcastSubmission' : ActorMethod<[Principal], undefined>,
  'unblockUserSongSubmission' : ActorMethod<[Principal], undefined>,
  'updateArtistProfile' : ActorMethod<
    [string, SaveArtistProfileInput],
    undefined
  >,
  'updateSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'updateTopVibingSong' : ActorMethod<[TopVibingSong], undefined>,
  'updateUserCategory' : ActorMethod<[Principal, UserCategory], undefined>,
  'updateVerificationStatus' : ActorMethod<
    [string, VerificationStatus, bigint],
    undefined
  >,
  'updateVideoStatus' : ActorMethod<
    [string, VideoSubmissionStatus, [] | [string]],
    undefined
  >,
  'updateVideoSubmission' : ActorMethod<
    [VideoSubmissionInput, string],
    undefined
  >,
  'upgradeUserToTeamMember' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];